name: multipart
description: A dart package for decoding multipart/form-data 
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bytes_io:
  path:
  nanoid:

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
